import "./styles/fonts.css"; // Google Fonts for built-in themes
import "./styles/tokens.css"; // active theme — generated by scaffold (see THEMES.md)
import "./styles/base.css";
import "./styles/animations.css";

import { useCallback, useEffect, useRef } from "react";
import { AutoStartGate } from "./components/AutoStartGate";
import { AutoToggle } from "./components/AutoToggle";
import { ProgressBar } from "./components/ProgressBar";
import { Stage } from "./components/Stage";
import { useAudioPlayer } from "./hooks/useAudioPlayer";
import { useAutoMode } from "./hooks/useAutoMode";
import { useStepper } from "./hooks/useStepper";
import { CHAPTERS } from "./registry/chapters";
import Ticiban from "./pages/Ticiban";

/**
 * Estimate spoken duration of a Chinese narration string. Native pace
 * ≈ 4 char/s → 250ms per char. Used as Auto-mode fallback ONLY when the
 * audio file is missing / fails / the narration is empty. When audio plays
 * normally, this value is unused — auto-advance fires on `audio.ended`.
 */
function estimateMs(text: string): number {
  if (!text) return 1500;
  return Math.max(1500, text.length * 250);
}

/**
 * 消息协议
 */
interface SyncMessage {
  type: "step-change" | "control";
  chapterId?: string;
  step?: number;
  action?: "prev" | "next" | "jump" | "ping";
  targetChapterId?: string;
  targetStep?: number;
}

export default function App() {
  // 路由检测：如果是提词板页面，直接渲染提词板
  const pathname = window.location.pathname;
  if (pathname === "/ticiban" || pathname === "/ticiban/") {
    return <Ticiban />;
  }

  const stepper = useStepper(CHAPTERS);
  const ch = CHAPTERS[stepper.cursor.chapter]!;
  const Cmp = ch.Component;
  const stepText = ch.narrations[stepper.cursor.step] ?? "";

  const { mode, cycleMode, autoStarted, setAutoStarted } = useAutoMode();

  // stepperRef 解决 useEffect([], []) 中闭包捕获初始值的问题
  const stepperRef = useRef(stepper);
  stepperRef.current = stepper;

  // BroadcastChannel 引用
  const channelRef = useRef<BroadcastChannel | null>(null);

  // 初始化 BroadcastChannel（只执行一次）
  useEffect(() => {
    const channel = new BroadcastChannel("presentation-sync");
    channelRef.current = channel;

    // 监听来自提词板的消息
    channel.onmessage = (event: MessageEvent<SyncMessage>) => {
      if (event.data.type === "control") {
        const { action, targetChapterId, targetStep } = event.data;

        switch (action) {
          case "next":
            stepperRef.current.next();
            break;
          case "prev":
            stepperRef.current.prev();
            break;
          case "jump":
            if (targetChapterId !== undefined) {
              const chapterIndex = CHAPTERS.findIndex(
                (ch) => ch.id === targetChapterId
              );
              if (chapterIndex !== -1) {
                stepperRef.current.jumpToChapter(chapterIndex, targetStep ?? 0);
              }
            }
            break;
          case "ping":
            // 提词板请求当前状态，发送当前 cursor
            const currentCh = CHAPTERS[stepperRef.current.cursor.chapter];
            if (currentCh) {
              channel.postMessage({
                type: "step-change",
                chapterId: currentCh.id,
                step: stepperRef.current.cursor.step,
              });
            }
            break;
        }
      }
    };

    return () => {
      channel.close();
    };
  }, []);

  // cursor 变化时广播给提词板
  useEffect(() => {
    if (channelRef.current && ch) {
      channelRef.current.postMessage({
        type: "step-change",
        chapterId: ch.id,
        step: stepper.cursor.step,
      });
    }
  }, [ch, stepper.cursor.step]);

  // Audio path follows the convention: /audio/<chapter-id>/<step+1>.mp3
  // (1-indexed file names match what `extract-narrations.ts` outputs.)
  // Empty narration → no audio src, Auto mode falls back to estimate.
  const audioSrc =
    mode === "manual" || stepText === ""
      ? null
      : `${import.meta.env.BASE_URL}audio/${ch.id}/${stepper.cursor.step + 1}.mp3`;

  const onAutoAdvance = useCallback(() => stepper.next(), [stepper]);

  useAudioPlayer({
    src: audioSrc,
    mode,
    trailMs: 200,
    estimateFallbackMs: estimateMs(stepText),
    onAutoAdvance,
    autoStarted,
  });

  return (
    <>
      <Stage onAdvance={stepper.next}>
        <div key={ch.id} className="scene">
          <Cmp step={stepper.cursor.step} />
        </div>
      </Stage>
      <ProgressBar
        chapters={CHAPTERS}
        cursor={stepper.cursor}
        onJumpChapter={stepper.jumpToChapter}
      />
      <AutoToggle mode={mode} onCycle={cycleMode} />
      <AutoStartGate
        visible={mode === "auto" && !autoStarted}
        onStart={() => setAutoStarted(true)}
      />
    </>
  );
}
