import "./styles/fonts.css"; // Google Fonts for built-in themes
import "./styles/tokens.css"; // active theme — generated by scaffold (see THEMES.md)
import "./styles/base.css";
import "./styles/animations.css";

import { useCallback, useEffect, useRef } from "react";
import { AutoStartGate } from "./components/AutoStartGate";
import { AutoToggle } from "./components/AutoToggle";
import { ProgressBar } from "./components/ProgressBar";
import { Stage } from "./components/Stage";
import { useAudioPlayer } from "./hooks/useAudioPlayer";
import { useAutoMode } from "./hooks/useAutoMode";
import { useStepper } from "./hooks/useStepper";
import { CHAPTERS } from "./registry/chapters";
import Ticiban from "./pages/Ticiban";

// 提词板路由：/ticiban → 渲染 Ticiban 组件
const pathname = window.location.pathname;

/**
 * Estimate spoken duration of a Chinese narration string. Native pace
 * ≈ 4 char/s → 250ms per char. Used as Auto-mode fallback ONLY when the
 * audio file is missing / fails / the narration is empty. When audio plays
 * normally, this value is unused — auto-advance fires on `audio.ended`.
 */
function estimateMs(text: string): number {
  if (!text) return 1500;
  return Math.max(1500, text.length * 250);
}

export default function App() {
  // 提词板路由
  if (pathname === "/ticiban" || pathname === "/ticiban/") {
    return <Ticiban />;
  }

  const stepper = useStepper(CHAPTERS);
  const ch = CHAPTERS[stepper.cursor.chapter]!;
  const Cmp = ch.Component;
  const stepText = ch.narrations[stepper.cursor.step] ?? "";

  const { mode, cycleMode, autoStarted, setAutoStarted } = useAutoMode();

  // stepperRef 解决 useEffect([], []) 中闭包捕获初始值的问题
  const stepperRef = useRef(stepper);
  stepperRef.current = stepper;

  // BroadcastChannel: 向提词板广播当前 step
  const channelRef = useRef<BroadcastChannel | null>(null);

  useEffect(() => {
    const channel = new BroadcastChannel("presentation-sync");
    channelRef.current = channel;

    // 接收提词板的控制指令
    channel.onmessage = (event) => {
      const data = event.data;
      if (data.type === "control") {
        if (data.action === "jump") {
          stepperRef.current.jumpToChapter(data.targetChapter, data.targetStep);
        } else if (data.action === "ping") {
          // 提词板打开时请求当前状态，回复之
          const cur = stepperRef.current.cursor;
          channel.postMessage({
            type: "step-change",
            chapter: cur.chapter,
            step: cur.step,
          });
        }
      }
    };

    return () => {
      channel.close();
    };
  }, []);

  // cursor 变化时广播给提词板
  useEffect(() => {
    channelRef.current?.postMessage({
      type: "step-change",
      chapter: stepper.cursor.chapter,
      step: stepper.cursor.step,
    });
  }, [stepper.cursor.chapter, stepper.cursor.step]);

  // Audio path follows the convention: /audio/<chapter-id>/<step+1>.mp3
  // (1-indexed file names match what `extract-narrations.ts` outputs.)
  // Empty narration → no audio src, Auto mode falls back to estimate.
  const audioSrc =
    mode === "manual" || stepText === ""
      ? null
      : `${import.meta.env.BASE_URL}audio/${ch.id}/${stepper.cursor.step + 1}.mp3`;

  const onAutoAdvance = useCallback(() => stepper.next(), [stepper]);

  useAudioPlayer({
    src: audioSrc,
    mode,
    trailMs: 200,
    estimateFallbackMs: estimateMs(stepText),
    onAutoAdvance,
    autoStarted,
  });

  return (
    <>
      <Stage onAdvance={stepper.next}>
        <div key={ch.id} className="scene">
          <Cmp step={stepper.cursor.step} />
        </div>
      </Stage>
      <ProgressBar
        chapters={CHAPTERS}
        cursor={stepper.cursor}
        onJumpChapter={stepper.jumpToChapter}
      />
      <AutoToggle mode={mode} onCycle={cycleMode} />
      <AutoStartGate
        visible={mode === "auto" && !autoStarted}
        onStart={() => setAutoStarted(true)}
      />
    </>
  );
}
